---
# Ansible scripts for deploying a DAOS client node

- name: Base DAOS configuration
  import_tasks: daos_base.yml

- name: Install DAOS client dependency packages
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version}}/clients_dependencies.yml"

- name: Update systemd service for daos-admin
  remote_user: root
  template:
    src: daos_agent.service.j2
    dest: /usr/lib/systemd/system/daos_agent.service
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Create base DAOS client configuration file tree
  remote_user: root
  file:
    path: /etc/daos/certs
    state: directory
    owner: root
    group: root
    mode: '0755'
    recurse: yes

- name: Configure MPI module
  import_tasks: openmpi_module.yml
