{
 "title": "DAOS With Scrubbing",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Checksum Scrubbing",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(engine_pool_scrubber_csums_total{}[$__interval])"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without (rank, pool, target) (rate(engine_pool_xferred_fetch[15s]))",
     "legendFormat": "Fetch"
    },
    {
     "expr": "sum without (rank, pool, target) (rate(engine_pool_xferred_update[15s]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum without (rank, pool) (rate(engine_pool_xferred_fetch[15s]) + rate(engine_pool_xferred_update[15s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "I/O Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum without (rank, pool, target) (rate(engine_pool_ops_fetch[1m]))",
     "legendFormat": "Fetch"
    },
    {
     "expr": "sum without (rank, pool, target) (rate(engine_pool_ops_update[1m]))",
     "legendFormat": "Update"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Ranks",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(engine_rank)" }
     ]
    },
    {
     "title": "Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without (rank) (ceil(rate(engine_events_dead_ranks[15s])))",
       "legendFormat": "Rank died"
      }
     ]
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Average Fetch Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg without (rank, target) (engine_io_latency_fetch_mean)",
     "legendFormat": "{{size}}"
    }
   ]
  },
  {
   "title": "Average Update Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg without (rank, target) (engine_io_latency_update_mean)",
     "legendFormat": "{{size}}"
    }
   ]
  },
  { "title": "Pools and Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Open Pool Handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum without (rank, pool) (engine_pool_pool_handles)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Open Container Handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum without (rank, job, instance, pool) (engine_pool_container_handles)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Container Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum without (rank, pool) (rate(engine_pool_ops_cont_open[15s]))",
     "legendFormat": "Open"
    },
    {
     "expr": "sum without (rank, pool) (rate(engine_pool_ops_cont_close[15s]))",
     "legendFormat": "Close"
    },
    {
     "expr": "sum without (rank, pool) (rate(engine_pool_ops_cont_destroy[15s]))",
     "legendFormat": "Destroy"
    }
   ]
  }
 ]
}